/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
});
export const LoginResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ProductId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'read' : IDL.Null,
  'completed' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'customerPhone' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const RatingEntry = IDL.Record({
  'createdAt' : IDL.Int,
  'productId' : IDL.Nat,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'notes' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Product],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'fixProductImages' : IDL.Func([IDL.Text, IDL.Vec(ProductId)], [], []),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductAverageRating' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getProductRatings' : IDL.Func([IDL.Nat], [IDL.Vec(RatingEntry)], ['query']),
  'markOrderCompleted' : IDL.Func([IDL.Text, OrderId], [IDL.Opt(Order)], []),
  'markOrderRead' : IDL.Func([IDL.Text, OrderId], [IDL.Opt(Order)], []),
  'placeOrder' : IDL.Func([OrderInput], [Order], []),
  'rateProduct' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'toggleProduct' : IDL.Func([IDL.Text, ProductId], [IDL.Opt(Product)], []),
  'updateProductImage' : IDL.Func(
      [IDL.Text, ProductId, IDL.Text],
      [IDL.Opt(Product)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
  });
  const LoginResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ProductId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'read' : IDL.Null,
    'completed' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'customerPhone' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const RatingEntry = IDL.Record({
    'createdAt' : IDL.Int,
    'productId' : IDL.Nat,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'notes' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Product],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'fixProductImages' : IDL.Func([IDL.Text, IDL.Vec(ProductId)], [], []),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getProductAverageRating' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getProductRatings' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RatingEntry)],
        ['query'],
      ),
    'markOrderCompleted' : IDL.Func([IDL.Text, OrderId], [IDL.Opt(Order)], []),
    'markOrderRead' : IDL.Func([IDL.Text, OrderId], [IDL.Opt(Order)], []),
    'placeOrder' : IDL.Func([OrderInput], [Order], []),
    'rateProduct' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'toggleProduct' : IDL.Func([IDL.Text, ProductId], [IDL.Opt(Product)], []),
    'updateProductImage' : IDL.Func(
        [IDL.Text, ProductId, IDL.Text],
        [IDL.Opt(Product)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };