/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type LoginResult = { 'ok' : string } |
  { 'err' : string };
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'customerPhone' : string,
  'createdAt' : bigint,
  'notes' : string,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderInput {
  'customerName' : string,
  'customerPhone' : string,
  'notes' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'read' : null } |
  { 'completed' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
}
export type ProductId = bigint;
export interface RatingEntry {
  'createdAt' : bigint,
  'productId' : bigint,
  'comment' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[string, string, string, string], Product>,
  'adminLogin' : ActorMethod<[string, string], LoginResult>,
  'fixProductImages' : ActorMethod<[string, Array<ProductId>], undefined>,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllOrders' : ActorMethod<[string], Array<Order>>,
  'getAllProducts' : ActorMethod<[string], Array<Product>>,
  'getProductAverageRating' : ActorMethod<[bigint], [] | [number]>,
  'getProductRatings' : ActorMethod<[bigint], Array<RatingEntry>>,
  'markOrderCompleted' : ActorMethod<[string, OrderId], [] | [Order]>,
  'markOrderRead' : ActorMethod<[string, OrderId], [] | [Order]>,
  'placeOrder' : ActorMethod<[OrderInput], Order>,
  'rateProduct' : ActorMethod<[bigint, bigint, string], undefined>,
  'toggleProduct' : ActorMethod<[string, ProductId], [] | [Product]>,
  'updateProductImage' : ActorMethod<
    [string, ProductId, string],
    [] | [Product]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];